# Generated by Django 5.2.1 on 2025-10-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=255)),
                ('answer_en', models.TextField()),
                ('answer_hi', models.TextField(blank=True)),
                ('answer_hinglish', models.TextField(blank=True)),
            ],
        ),
    ]
