# Generated by Django 5.2.1 on 2025-10-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotquery',
            name='category',
            field=models.CharField(choices=[('GREETING', 'Greeting'), ('META', 'About Bot'), ('ERP', 'ERP Question'), ('PAGE_HELP', 'Page Specific Help')], default='ERP', max_length=10),
        ),
        migrations.AddField(
            model_name='chatbotquery',
            name='page_identifier',
            field=models.CharField(blank=True, help_text="e.g., '/about', '/login'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chatbotquery',
            name='keywords',
            field=models.CharField(help_text="Comma-separated keywords, e.g., 'fees,cost,admission fee'", max_length=255),
        ),
    ]
